# Generated by Django 4.1.5 on 2023-01-29 21:34

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_produto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to='fotos/%Y/%m/%d', variations={'thumbnail': {'height': 500, 'width': 500}}),
        ),
    ]
