# Generated by Django 4.1.5 on 2023-01-29 23:01

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to='fotos/%Y/%m/%d', variations={'thumbnail': {'height': 700, 'width': 700}}),
        ),
    ]
